# .github/workflows/build-with-db.yml
name: Build and Release (With Database Version)

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_db.txt
        pip install pyinstaller
    
    - name: Build executable
      run: |
        pyinstaller main_with_db.spec
    
    - name: List output files
      run: Get-ChildItem -Path ./dist -Force # <-- COMANDO CORREGIDO PARA WINDOWS
    
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: face_recognition_with_db_exe
        path: ./dist/face_recognition_with_db.exe
    
    - name: Release and Upload Executable
      uses: softprops/action-gh-release@v1
      with:
        name: Database Version Build #${{ github.run_number }}
        tag_name: db-nightly-${{ github.run_number }}
        body: |
          VersiÃ³n con base de datos y carga de fotos.
          **Build:** #${{ github.run_number }}
          **Commit:** [${{ github.sha }}](${{ github.sha }})
          
          Permite subir y gestionar fotos en la base de datos local.
        prerelease: true
        files: ./dist/face_recognition_with_db.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
